### ISSUE TITLE
INFO exited: nodepki (exit status 1; not expected)

### ISSUE THREAD

**Issue by PhilipSchmid** [aditosoftware/nodepki-docker#11]
Hi there,

I tried to run `nodepki-docker` but the nodepki server seems to crash every time `docker-compose up` entered.

# Steps to reproduce

Clone the repo:
```bash
git clone git@github.com:aditosoftware/nodepki-docker.git
```

Edit `docker-compose.yml`:
```yml
version: '3.4'

services:
  nodepki:
    image: adito/nodepki-docker
    ports:
      - "8080:8080"
      - "2560:2560"
      - "5000:5000"
      - "5858:5858"
    volumes:
      - "/opt/data/nodepki/nodepki:/root/nodepki/data"
      - "/opt/data/nodepki/nodepki-client/:/root/nodepki-client/data"
      - "/opt/data/nodepki/nodepki-webclient/:/root/nodepki-webclient/data"
      - "/opt/data/nodepki/certs/:/root/nodepki-client/out"
    extra_hosts:
      - "ca.example.com:127.0.0.1"
      - "ocsp.example.com:127.0.0.1"
      - "ca-admin.example.com:127.0.0.1"
    environment:
      API_USERNAME: localadmin
      API_PASSWORD: top_secret
    labels:
      traefik.ca-admin.port: 5000
      traefik.ca-admin.frontend.rule: Host:ca-admin.example.com
      traefik.ca-admin.protocol: http
      traefik.ca.port: 8080
      traefik.ca.frontend.rule: Host:ca.example.com
      traefik.ca.protocol: http
      traefik.ocsp.port: 2560
      traefik.ocsp.frontend.rule: Host:ocsp.example.com
      traefik.ocsp.protocol: http
```

Let the basic config generate:
```bash
[root@node01]# docker-compose run nodepki /bin/sh /root/setup.sh
>>>>>> Setting up NodePKI-Client ...
>>>>>> Setting up NodePKI-Webclient ...
>>>>>> Setting up NodePKI ...
[14:21:15] User created successfully.
>>>>>> Setup finished.
```

Edited the configuration `nodepki/config/config.yml`:
```yml
###
### Server config: IP-Address and port to listen to.
###

server:
    ip: 0.0.0.0
    http:
        domain: ca.example.com
        port: 8080
    ocsp:
        domain: ocsp.example.com
        port: 2560



###
### CA config: Passphrase for CA Key
###

ca:
    root:
        passphrase: <secret>
        days: 3650
        country: CH
        state: Zurich
        locality: Zurich
        organization: Example GmbH
        commonname: Root CA
    intermediate:
        passphrase: <secret>
        days: 3650
        country: CH
        state: Zurich
        locality: Zurich
        organization: Example ORG
        commonname: Intermediate CA
        ocsp:
            passphrase: <secret>
            country: CH
            url: "https://ocsp.example.com"
        crl:
            url: "https://ca.example.com/public/ca/intermediate/crl"


###
### Settings for end user certificates
###
cert:
    lifetime_default: 1
    lifetime_max: 1095
```

Start of nodepki: 
```bash
[root@node01]# docker-compose up
Recreating nodepki_nodepki_1 ... done
Attaching to nodepki_nodepki_1
nodepki_1  | 2018-04-28 14:23:16,479 CRIT Supervisor running as root (no user in config file)
nodepki_1  | 2018-04-28 14:23:16,482 INFO supervisord started with pid 7
nodepki_1  | 2018-04-28 14:23:17,484 INFO spawned: 'nodepki' with pid 10
nodepki_1  | 2018-04-28 14:23:17,485 INFO spawned: 'nodepki_webclient' with pid 11
nodepki_1  | 2018-04-28 14:23:17,936 INFO exited: nodepki (exit status 1; not expected)
nodepki_1  | 2018-04-28 14:23:18,938 INFO spawned: 'nodepki' with pid 32
nodepki_1  | 2018-04-28 14:23:18,939 INFO success: nodepki_webclient entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
nodepki_1  | 2018-04-28 14:23:19,350 INFO exited: nodepki (exit status 1; not expected)
nodepki_1  | 2018-04-28 14:23:21,354 INFO spawned: 'nodepki' with pid 48
nodepki_1  | 2018-04-28 14:23:21,761 INFO exited: nodepki (exit status 1; not expected)
nodepki_1  | 2018-04-28 14:23:24,764 INFO spawned: 'nodepki' with pid 64
nodepki_1  | 2018-04-28 14:23:25,169 INFO exited: nodepki (exit status 1; not expected)
nodepki_1  | 2018-04-28 14:23:26,171 INFO gave up: nodepki entered FATAL state, too many start retries too quickly
```

Do you guys have any guess that the issue could be? I guess its something with the configuration but I don't have any clue what's wrong. The nodepki server unfortunately does not deliver a more specific error message.

Thanks!

Regards,
Philip

**Comment by PhilipSchmid** [comment]
Hi there, 
I now tried to debug the `server.js` with the following result:

```bash
~/nodepki # node-debug --web-host 172.18.0.2 server.js
Node Inspector v1.1.2
Visit http://172.18.0.2:8080/?port=5858 to start debugging.
Debugging `server.js`

No browser matching [chrome,chromium,opera] found in the system! If this is not true, submit a bug report on https://github.com/benderjs/browser-launcher2
Please open the URL manually in Chrome/Chromium/Opera or similar browser
(node:175) DeprecationWarning: node --debug is deprecated. Please use node --inspect instead.
Debugger listening on 127.0.0.1:5858

[14:48:53] NodePKI is starting up ...
  _   _           _      ____  _  _____ 
 | \ | | ___   __| | ___|  _ \| |/ /_ _|
 |  \| |/ _ \ / _` |/ _ \ |_) | ' / | | 
 | |\  | (_) | (_| |  __/  __/| . \ | | 
 |_| \_|\___/ \__,_|\___|_|   |_|\_\___|
                                        
  By ADITO Software GmbH


[14:48:53] Reading config file data/config/config.yml ...
[14:48:53] Reindexing CertDB ...
[14:49:23] Starting OCSP server ...
[14:49:23] >>>>>> OCSP server is listening on 0.0.0.0:2560 <<<<<<
[14:49:23] Server started.
[14:49:23] OCSP-Server is running
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at Pipe.onread (net.js:582:26)
```

This exception happens somewhere at https://github.com/aditosoftware/nodepki/blob/54ed31d684592f17b5e7c9966d5b67ae6e5a661e/certdb.js#L48 as I found out using break points in the `node-debug` web UI. Any guesses where this comes from regarding the configuration above?

Thanks.

Regards,
Philip

**Comment by PhilipSchmid** [comment]
Hi there,

I finally found the issue... The problem was, when the Intermediate `organization` (`organization: Example ORG`) differs from the root `organization` (`organization: Example GmbH`) the exception above is thrown and the `server.js` crashes.

Fixed configuration:
```yml
ca:
    root:
        passphrase: <secret>
        days: 3650
        country: CH
        state: Zurich
        locality: Zurich
        organization: Example GmbH
        commonname: Root CA
    intermediate:
        passphrase: <secret>
        days: 3650
        country: CH
        state: Zurich
        locality: Zurich
        organization: Example GmbH
        commonname: Intermediate CA
        ocsp:
            passphrase: <secret>
            country: CH
            url: "http://ocsp.example.com"
        crl:
            url: "http://ca.example.com/public/ca/intermediate/crl"
```
Is it required to define both `organization`'s exactly the same or is this a bug which isn't handled by the software yet? Nevertheless, this SHOULD be documented!

Thanks.

Regards,
Philip
